name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [6, 7, 8]
        experimental: [false]
        include:
          - version: 9
            experimental: true
    steps:
      - name: running
        run: echo "running job with ${{ matrix.version }} ${{ matrix.experimental }}"
  lint:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [6, 7, 8]
        experimental: [false]
        include:
          - version: 9
            experimental: true
    steps:
      - name: running
        run: echo "running job with ${{ matrix.version }} ${{ matrix.experimental }}"
            
  unit_test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [6, 7, 8]
        experimental: [false]
        include:
          - version: 9
            experimental: true
    steps:
      - name: running
        run: echo "running job with ${{ matrix.version }} ${{ matrix.experimental }}"
