name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [6, 7, 8]
        experimental: [false]
        include:
          - version: 9
            experimental: true
    steps:
      - name: running
        run: echo "running job with ${{ matrix.version }} ${{ matrix.experimental }}"
        
  lint:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [6, 7, 8]
        experimental: [false]
        include:
          - version: 9
            experimental: true
    steps:
      - name: running
        run: echo "running job with ${{ matrix.version }} ${{ matrix.experimental }}"; if [ ${{ matrix.version }} == 6 ]; then exit 1; fi
            
  unit_test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [6, 7, 8]
        experimental: [false]
        include:
          - version: 9
            experimental: true
    steps:
      - name: running
        run: echo "running job with ${{ matrix.version }} ${{ matrix.experimental }}"
        
  after_jobs:
    needs: [lint, build, unit_test]
    runs-on: ubuntu-latest
    if: success() # only run when all shards have passed
    outputs:
      success: ${{ steps.setoutput.outputs.success }}
    steps:
      - id: setoutput
        run: echo "::set-output name=success::true"
